language: python

python:
  - "2.7"

services:
  - redis-server

install:
  - pip install -r .travis-requirements.txt

script:
  - "./run_tests.py"

notifications:
  email:
    recipients:
      - build@pjuu.com
