language: python

python:
  - '2.7'

services:
  - mongodb
  - redis-server

before_install:
  - sudo apt-get update
  - sudo apt-get install libtiff4-dev libjpeg8-dev zlib1g-dev libfreetype6-dev liblcms2-dev libwebp-dev tcl8.5-dev tk8.5-dev python-tk

install:
  - pip install -r requirements-dev.txt

script:
  - coverage run --source=pjuu --omit=pjuu/wsgi.py,*.html,*.txt --branch run_tests.py

after_success:
  - coveralls

notifications:
  email: false
  webhooks:
    secure: "Cb89mDzNT+ME9ExMfVvaiG29gRGn7hTVyrLwVRKErRm1oP6zi4zNELdlgA/eRtpQIzqZ5SXLkUgMzuKQ6JJvB52boID4WpNZNFPKtRyYd6gTVO96ZkWouoeOcs3kF6TOf2HeLwiVTLzXlSd8kxLsLMPQt7fXQAR0roEAHOzzy2Q="
    on_success: always
    on_failure: always
    on_start: false
