language: python

python:
  - '2.7'
  - 'pypy'

# Enable container based deploys
sudo: false

services:
  - mongodb
  - redis-server

before_install:
  - sudo apt-get update
  - sudo apt-get install libtiff4-dev libjpeg8-dev zlib1g-dev libfreetype6-dev liblcms2-dev libwebp-dev tcl8.5-dev tk8.5-dev python-tk

install:
  - pip install -r requirements-dev.txt

script:
  - flake8 --exclude=docs,venv .
  - coverage run --source=pjuu --omit=pjuu/wsgi.py,*.html,*.txt --branch run_tests.py

after_success:
  - coveralls

notifications:
  email: false
  webhooks:
    urls:
      - secure: "GJVuWZAJIekY1skbh4LMgxhYs4foYnRFME/lBFjmE5W1S96C//xvuchBbSls/8NDg+6397ZZpqxUNPkDWCljvL0ieantM8u4qMd/pBFbplqRd/FsAexJaEzkuPO0cVDniHCaDqEVzwDeXxpqJqyJP1NaxV/4Jx/bBlTNj73WqkI="
    on_success: always
    on_failure: always
    on_start: never
