language: python

python:
  - '2.7'

services:
  - redis-server

install:
  - pip install -r requirements.txt

script:
  - coverage run --source=pjuu --omit=*/tests.py run_tests.py

after_success:
  - coveralls

notifications:
  hipchat:
    secure: "oT27TGIlAvHgtRUBejYapmt95o/q1wVRWGWh7npbPspAwWfxKVF3ZudrPR+FPx+THGNkBRiS3uxrVML6/aY2tEog6JmhhcSENz9uvBlvc6cGBgD3HGLhn1m/LX71ul73HwR8CLofqpZo3d3TqiXdbPZONUzkMQHs3NYSjB4qoto="
